// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAnswer = `-- name: InsertAnswer :execrows
INSERT INTO answers (room_player_id, question_id, served_at, answered_at, option_id, correct, points)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (room_player_id, question_id) DO NOTHING
`

type InsertAnswerParams struct {
	RoomPlayerID uuid.UUID
	QuestionID   string
	ServedAt     pgtype.Timestamptz
	AnsweredAt   pgtype.Timestamptz
	OptionID     pgtype.Text
	Correct      pgtype.Bool
	Points       int16
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAnswer,
		arg.RoomPlayerID,
		arg.QuestionID,
		arg.ServedAt,
		arg.AnsweredAt,
		arg.OptionID,
		arg.Correct,
		arg.Points,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlayerProgress = `-- name: UpdatePlayerProgress :exec
UPDATE room_players
SET score = $2, correct_count = $3, total_ms = $4, current_index = $5, streak = $6,
    finished_at = CASE WHEN $7::bool THEN COALESCE(finished_at, NOW()) ELSE finished_at END
WHERE id = $1
`

type UpdatePlayerProgressParams struct {
	ID           uuid.UUID
	Score        int32
	CorrectCount int16
	TotalMs      int32
	CurrentIndex int16
	Streak       int16
	Column7      bool
}

func (q *Queries) UpdatePlayerProgress(ctx context.Context, arg UpdatePlayerProgressParams) error {
	_, err := q.db.Exec(ctx, updatePlayerProgress,
		arg.ID,
		arg.Score,
		arg.CorrectCount,
		arg.TotalMs,
		arg.CurrentIndex,
		arg.Streak,
		arg.Column7,
	)
	return err
}
