// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getHostByEmail = `-- name: GetHostByEmail :one
SELECT id, email, password_hash, name FROM host_users WHERE email = $1
`

type GetHostByEmailRow struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) GetHostByEmail(ctx context.Context, email string) (GetHostByEmailRow, error) {
	row := q.db.QueryRow(ctx, getHostByEmail, email)
	var i GetHostByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
	)
	return i, err
}

const touchHostLogin = `-- name: TouchHostLogin :exec
UPDATE host_users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) TouchHostLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchHostLogin, id)
	return err
}

const upsertHost = `-- name: UpsertHost :exec
INSERT INTO host_users (email, password_hash, name)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    name          = EXCLUDED.name
`

type UpsertHostParams struct {
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) error {
	_, err := q.db.Exec(ctx, upsertHost, arg.Email, arg.PasswordHash, arg.Name)
	return err
}
