// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	RoomPlayerID uuid.UUID
	QuestionID   string
	ServedAt     pgtype.Timestamptz
	AnsweredAt   pgtype.Timestamptz
	OptionID     pgtype.Text
	Correct      pgtype.Bool
	Points       int16
}

type HostUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
}

type Question struct {
	ID          string
	Site        int16
	Level       int16
	Type        string
	Prompt      []byte
	Options     []byte
	Explanation []byte
	Active      bool
	ReviewFlag  bool
	CreatedAt   pgtype.Timestamptz
}

type Room struct {
	ID           uuid.UUID
	Pin          string
	HostID       uuid.UUID
	Jenjang      string
	ShortSession bool
	AccuracyMode bool
	Status       string
	QuestionIds  []string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
}

type RoomPlayer struct {
	ID           uuid.UUID
	RoomID       uuid.UUID
	Nickname     string
	SchoolID     pgtype.Int4
	Jenjang      string
	Avatar       int16
	Lang         string
	Score        int32
	CorrectCount int16
	TotalMs      int32
	CurrentIndex int16
	Streak       int16
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type School struct {
	ID        int32
	Name      string
	Jenjang   pgtype.Text
	City      pgtype.Text
	Verified  bool
	CreatedAt pgtype.Timestamptz
}
