// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRoomPlayers = `-- name: CountRoomPlayers :one
SELECT COUNT(*) FROM room_players WHERE room_id = $1
`

func (q *Queries) CountRoomPlayers(ctx context.Context, roomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPlayers, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM room_players WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const insertPlayer = `-- name: InsertPlayer :one
INSERT INTO room_players (room_id, nickname, school_id, jenjang, avatar, lang)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertPlayerParams struct {
	RoomID   uuid.UUID
	Nickname string
	SchoolID pgtype.Int4
	Jenjang  string
	Avatar   int16
	Lang     string
}

func (q *Queries) InsertPlayer(ctx context.Context, arg InsertPlayerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlayer,
		arg.RoomID,
		arg.Nickname,
		arg.SchoolID,
		arg.Jenjang,
		arg.Avatar,
		arg.Lang,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT rp.id, rp.nickname, rp.avatar, rp.lang, COALESCE(s.name, '')::text AS school_name,
       rp.score, rp.correct_count, rp.total_ms, rp.current_index, rp.streak, (rp.finished_at IS NOT NULL)::bool AS finished
FROM room_players rp
LEFT JOIN schools s ON s.id = rp.school_id
WHERE rp.room_id = $1
ORDER BY rp.created_at
`

type ListRoomPlayersRow struct {
	ID           uuid.UUID
	Nickname     string
	Avatar       int16
	Lang         string
	SchoolName   string
	Score        int32
	CorrectCount int16
	TotalMs      int32
	CurrentIndex int16
	Streak       int16
	Finished     bool
}

func (q *Queries) ListRoomPlayers(ctx context.Context, roomID uuid.UUID) ([]ListRoomPlayersRow, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomPlayersRow
	for rows.Next() {
		var i ListRoomPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.Avatar,
			&i.Lang,
			&i.SchoolName,
			&i.Score,
			&i.CorrectCount,
			&i.TotalMs,
			&i.CurrentIndex,
			&i.Streak,
			&i.Finished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
