// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package queries

import (
	"context"
)

const listSelectableQuestions = `-- name: ListSelectableQuestions :many
SELECT id, site, level FROM questions WHERE active = TRUE AND site BETWEEN 1 AND 5 ORDER BY id
`

type ListSelectableQuestionsRow struct {
	ID    string
	Site  int16
	Level int16
}

func (q *Queries) ListSelectableQuestions(ctx context.Context) ([]ListSelectableQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listSelectableQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSelectableQuestionsRow
	for rows.Next() {
		var i ListSelectableQuestionsRow
		if err := rows.Scan(&i.ID, &i.Site, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
