// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRooms = `-- name: CountActiveRooms :one
SELECT COUNT(*) FROM rooms
WHERE status != 'ended' AND created_at > NOW() - INTERVAL '2 hours'
`

func (q *Queries) CountActiveRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveRoomByPIN = `-- name: GetActiveRoomByPIN :one
SELECT id, pin, host_id, jenjang, short_session, accuracy_mode, status, question_ids, started_at
FROM rooms
WHERE pin = $1 AND status != 'ended'
`

type GetActiveRoomByPINRow struct {
	ID           uuid.UUID
	Pin          string
	HostID       uuid.UUID
	Jenjang      string
	ShortSession bool
	AccuracyMode bool
	Status       string
	QuestionIds  []string
	StartedAt    pgtype.Timestamptz
}

func (q *Queries) GetActiveRoomByPIN(ctx context.Context, pin string) (GetActiveRoomByPINRow, error) {
	row := q.db.QueryRow(ctx, getActiveRoomByPIN, pin)
	var i GetActiveRoomByPINRow
	err := row.Scan(
		&i.ID,
		&i.Pin,
		&i.HostID,
		&i.Jenjang,
		&i.ShortSession,
		&i.AccuracyMode,
		&i.Status,
		&i.QuestionIds,
		&i.StartedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, pin, host_id, jenjang, short_session, accuracy_mode, status, question_ids, started_at
FROM rooms
WHERE id = $1
`

type GetRoomByIDRow struct {
	ID           uuid.UUID
	Pin          string
	HostID       uuid.UUID
	Jenjang      string
	ShortSession bool
	AccuracyMode bool
	Status       string
	QuestionIds  []string
	StartedAt    pgtype.Timestamptz
}

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (GetRoomByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i GetRoomByIDRow
	err := row.Scan(
		&i.ID,
		&i.Pin,
		&i.HostID,
		&i.Jenjang,
		&i.ShortSession,
		&i.AccuracyMode,
		&i.Status,
		&i.QuestionIds,
		&i.StartedAt,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (pin, host_id, jenjang, short_session, accuracy_mode, question_ids)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertRoomParams struct {
	Pin          string
	HostID       uuid.UUID
	Jenjang      string
	ShortSession bool
	AccuracyMode bool
	QuestionIds  []string
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRoom,
		arg.Pin,
		arg.HostID,
		arg.Jenjang,
		arg.ShortSession,
		arg.AccuracyMode,
		arg.QuestionIds,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockRoomCreation = `-- name: LockRoomCreation :exec
SELECT pg_advisory_xact_lock(4201)
`

func (q *Queries) LockRoomCreation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRoomCreation)
	return err
}

const lockRoomForJoin = `-- name: LockRoomForJoin :one
SELECT id FROM rooms WHERE id = $1 AND status != 'ended' FOR UPDATE
`

func (q *Queries) LockRoomForJoin(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRoomForJoin, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markRoomEnded = `-- name: MarkRoomEnded :exec
UPDATE rooms SET status = 'ended', ended_at = NOW() WHERE id = $1 AND status != 'ended'
`

func (q *Queries) MarkRoomEnded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRoomEnded, id)
	return err
}

const markRoomStarted = `-- name: MarkRoomStarted :execrows
UPDATE rooms SET status = 'running', started_at = NOW() WHERE id = $1 AND status = 'lobby'
`

func (q *Queries) MarkRoomStarted(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRoomStarted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
