// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schools.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSchoolName = `-- name: GetSchoolName :one
SELECT name FROM schools WHERE id = $1
`

func (q *Queries) GetSchoolName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getSchoolName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listSchoolsByName = `-- name: ListSchoolsByName :many
SELECT id, name, jenjang FROM schools WHERE name = ANY($1::text[]) ORDER BY name
`

type ListSchoolsByNameRow struct {
	ID      int32
	Name    string
	Jenjang pgtype.Text
}

func (q *Queries) ListSchoolsByName(ctx context.Context, dollar_1 []string) ([]ListSchoolsByNameRow, error) {
	rows, err := q.db.Query(ctx, listSchoolsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolsByNameRow
	for rows.Next() {
		var i ListSchoolsByNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Jenjang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSchools = `-- name: SearchSchools :many
SELECT id, name, jenjang FROM schools
WHERE verified AND name != ALL($2::text[]) AND ($1::text = '' OR name ILIKE '%' || $1::text || '%')
ORDER BY name
LIMIT 20
`

type SearchSchoolsParams struct {
	Column1 string
	Column2 []string
}

type SearchSchoolsRow struct {
	ID      int32
	Name    string
	Jenjang pgtype.Text
}

func (q *Queries) SearchSchools(ctx context.Context, arg SearchSchoolsParams) ([]SearchSchoolsRow, error) {
	rows, err := q.db.Query(ctx, searchSchools, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSchoolsRow
	for rows.Next() {
		var i SearchSchoolsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Jenjang); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
