// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertQuestion = `-- name: UpsertQuestion :exec
INSERT INTO questions (id, site, level, type, prompt, options, explanation, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    site              = EXCLUDED.site,
    level             = EXCLUDED.level,
    type              = EXCLUDED.type,
    prompt            = EXCLUDED.prompt,
    options           = EXCLUDED.options,
    explanation       = EXCLUDED.explanation,
    active            = EXCLUDED.active
`

type UpsertQuestionParams struct {
	ID          string
	Site        int16
	Level       int16
	Type        string
	Prompt      []byte
	Options     []byte
	Explanation []byte
	Active      bool
}

func (q *Queries) UpsertQuestion(ctx context.Context, arg UpsertQuestionParams) error {
	_, err := q.db.Exec(ctx, upsertQuestion,
		arg.ID,
		arg.Site,
		arg.Level,
		arg.Type,
		arg.Prompt,
		arg.Options,
		arg.Explanation,
		arg.Active,
	)
	return err
}

const upsertSchool = `-- name: UpsertSchool :exec
INSERT INTO schools (name, jenjang, city, verified)
VALUES ($1, $2, $3, TRUE)
ON CONFLICT (name) DO UPDATE SET
    jenjang = EXCLUDED.jenjang,
    city    = EXCLUDED.city
`

type UpsertSchoolParams struct {
	Name    string
	Jenjang pgtype.Text
	City    pgtype.Text
}

func (q *Queries) UpsertSchool(ctx context.Context, arg UpsertSchoolParams) error {
	_, err := q.db.Exec(ctx, upsertSchool, arg.Name, arg.Jenjang, arg.City)
	return err
}
